name: Victhon
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/victhon_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/victhon_logo.png"



flutter_native_splash:
  color: "#ffffff" # Background color
  image: "assets/icons/victhon_logo.png" # Your app logo
  android: true
  ios: true
  # android_12:
  #   image: "assets/logo.png"
  #   icon_background_color: "#ffffff"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.0
  geolocator: ^13.0.2
  # geocode: ^1.0.3
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  google_maps_flutter_ios: ^2.13.2
  image_picker: ^1.1.2
  lucide_icons: ^0.257.0
  flutter_native_splash: ^2.4.4
  dartz: ^0.10.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  intl: 0.20.2
  socket_io_client: ^3.1.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  device_preview: ^1.1.0
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  smooth_page_indicator: ^1.2.1
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.6
  # flutter_local_notifications: ^19.2.1
  onesignal_flutter: ^5.3.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0

  # google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
