

import 'package:get/get.dart';

RxString country = ''.obs;
RxString state = ''.obs;
RxString city = ''.obs;
RxString street = ''.obs;

const List<String> countryList = [
  "Nigeria",
  "Germany",
  "Canada",
  "United States",
  "United Kingdom",
];

final nigeriaStateCitiesList = [
  {
    "state": "Abia",
    "cities": ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Isuikwuato"]
  },
  {
    "state": "Adamawa",
    "cities": ["Yola", "Mubi", "Jimeta", "Numan", "Ganye"]
  },
  {
    "state": "Akwa Ibom",
    "cities": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak"]
  },
  {
    "state": "Anambra",
    "cities": ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ozubulu"]
  },
  {
    "state": "Bauchi",
    "cities": ["Bauchi", "Azare", "Misau", "Jama'are", "Darazo"]
  },
  {
    "state": "Bayelsa",
    "cities": ["Yenagoa", "Brass", "Ogbia", "Sagbama", "Nembe"]
  },
  {
    "state": "Benue",
    "cities": ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya"]
  },
  {
    "state": "Borno",
    "cities": ["Maiduguri", "Biu", "Dikwa", "Monguno", "Chibok"]
  },
  {
    "state": "Cross River",
    "cities": ["Calabar", "Ikom", "Obudu", "Ogoja", "Ugep"]
  },
  {
    "state": "Delta",
    "cities": ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor"]
  },
  {
    "state": "Ebonyi",
    "cities": ["Abakaliki", "Afikpo", "Onueke", "Ezza", "Ohaukwu"]
  },
  {
    "state": "Edo",
    "cities": ["Benin cities", "Auchi", "Ekpoma", "Uromi", "Igueben"]
  },
  {
    "state": "Ekiti",
    "cities": ["Ado-Ekiti", "Ikere", "Ilawe", "Omuo", "Iyin-Ekiti"]
  },
  {
    "state": "Enugu",
    "cities": ["Enugu", "Nsukka", "Awgu", "Oji River", "Agbani"]
  },
  {
    "state": "Gombe",
    "cities": ["Gombe", "Kaltungo", "Billiri", "Dukku", "Bajoga"]
  },
  {
    "state": "Imo",
    "cities": ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta"]
  },
  {
    "state": "Jigawa",
    "cities": ["Dutse", "Hadejia", "Birnin Kudu", "Gumel", "Kazaure"]
  },
  {
    "state": "Kaduna",
    "cities": ["Kaduna", "Zaria", "Kafanchan", "Kagoro", "Saminaka"]
  },
  {
    "state": "Kano",
    "cities": ["Kano", "Wudil", "Bichi", "Gaya", "Rano"]
  },
  {
    "state": "Katsina",
    "cities": ["Katsina", "Daura", "Funtua", "Malumfashi", "Dutsin-Ma"]
  },
  {
    "state": "Kebbi",
    "cities": ["Birnin Kebbi", "Argungu", "Zuru", "Yauri", "Koko"]
  },
  {
    "state": "Kogi",
    "cities": ["Lokoja", "Okene", "Idah", "Ankpa", "Kabba"]
  },
  {
    "state": "Kwara",
    "cities": ["Ilorin", "Offa", "Omu-Aran", "Lafiagi", "Patigi"]
  },
  {
    "state": "Lagos",
    "cities": ["Ikeja", "Ikorodu", "Epe", "Badagry", "Victoria Island", "Lekki"]
  },
  {
    "state": "Nasarawa",
    "cities": ["Lafia", "Keffi", "Akwanga", "Doma", "Karu"]
  },
  {
    "state": "Niger",
    "cities": ["Minna", "Suleja", "Bida", "Kontagora", "Mokwa"]
  },
  {
    "state": "Ogun",
    "cities": ["Abeokuta", "Ijebu Ode", "Sango Ota", "Sagamu", "Ilaro"]
  },
  {
    "state": "Ondo",
    "cities": ["Akure", "Ondo", "Owo", "Ikare", "Okitipupa"]
  },
  {
    "state": "Osun",
    "cities": ["Oshogbo", "Ile-Ife", "Ilesa", "Ejigbo", "Ede"]
  },
  {
    "state": "Oyo",
    "cities": ["Ibadan", "Ogbomoso", "Oyo", "Iseyin", "Igboho"]
  },
  {
    "state": "Plateau",
    "cities": ["Jos", "Pankshin", "Barkin Ladi", "Shendam", "Langtang"]
  },
  {
    "state": "Rivers",
    "cities": ["Port Harcourt", "Bonny", "Omoku", "Ahoada", "Bori"]
  },
  {
    "state": "Sokoto",
    "cities": ["Sokoto", "Tambuwal", "Gwadabawa", "Bodinga", "Illela"]
  },
  {
    "state": "Taraba",
    "cities": ["Jalingo", "Wukari", "Takum", "Bali", "Gembu"]
  },
  {
    "state": "Yobe",
    "cities": ["Damaturu", "Potiskum", "Nguru", "Gashua", "Geidam"]
  },
  {
    "state": "Zamfara",
    "cities": ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Zurmi"]
  },
  {
    "state": "FCT",
    "cities": ["Abuja", "Gwagwalada", "Kubwa", "Karu", "Lugbe"]
  }
];

const usStateCitiesList = [
  {
    "state": "Alabama",
    "cities": [
      "Alexander cities",
      "Andalusia",
      "Anniston",
      "Athens",
      "Atmore",
      "Auburn",
      "Bessemer",
      "Birmingham",
      "Chickasaw",
      "Clanton",
      "Cullman",
      "Decatur",
      "Demopolis",
      "Dothan",
      "Enterprise",
      "Eufaula",
      "Florence",
      "Fort Payne",
      "Gadsden",
      "Greenville",
      "Guntersville",
      "Huntsville",
      "Jasper",
      "Marion",
      "Mobile",
      "Montgomery",
      "Opelika",
      "Ozark",
      "Phenix cities",
      "Prichard",
      "Scottsboro",
      "Selma",
      "Sheffield",
      "Sylacauga",
      "Talladega",
      "Troy",
      "Tuscaloosa",
      "Tuscumbia",
      "Tuskegee"
    ]
  },
  {
    "state": "Alaska",
    "cities": [
      "Anchorage",
      "Cordova",
      "Fairbanks",
      "Haines",
      "Homer",
      "Juneau",
      "Ketchikan",
      "Kodiak",
      "Kotzebue",
      "Nome",
      "Palmer",
      "Seward",
      "Sitka",
      "Skagway",
      "Valdez"
    ],
  },
  {
    "state": "Arizona",
    "cities": [
      "Ajo",
      "Avondale",
      "Bisbee",
      "Casa Grande",
      "Chandler",
      "Clifton",
      "Douglas",
      "Flagstaff",
      "Florence",
      "Gila Bend",
      "Glendale",
      "Globe",
      "Kingman",
      "Lake Havasu cities",
      "Mesa",
      "Nogales",
      "Oraibi",
      "Phoenix",
      "Prescott",
      "Scottsdale",
      "Sierra Vista",
      "Tempe",
      "Tombstone",
      "Tucson",
      "Walpi",
      "Window Rock",
      "Winslow",
      "Yuma"
    ],
  },
  {
    "state": "Arkansas",
    "cities": [
      "Arkadelphia",
      "Arkansas Post",
      "Batesville",
      "Benton",
      "Blytheville",
      "Camden",
      "Conway",
      "Crossett",
      "El Dorado",
      "Fayetteville",
      "Forrest cities",
      "Fort Smith",
      "Harrison",
      "Helena",
      "Hope",
      "Hot Springs",
      "Jacksonville",
      "Jonesboro",
      "Little Rock",
      "Magnolia",
      "Morrilton",
      "Newport",
      "North Little Rock",
      "Osceola",
      "Pine Bluff",
      "Rogers",
      "Searcy",
      "Stuttgart",
      "Van Buren",
      "West Memphis"
    ],
  },
  {
    "state": "California",
    "cities": [
      "Alameda",
      "Alhambra",
      "Anaheim",
      "Antioch",
      "Arcadia",
      "Bakersfield",
      "Barstow",
      "Belmont",
      "Berkeley",
      "Beverly Hills",
      "Brea",
      "Buena Park",
      "Burbank",
      "Calexico",
      "Calistoga",
      "Carlsbad",
      "Carmel",
      "Chico",
      "Chula Vista",
      "Claremont",
      "Compton",
      "Concord",
      "Corona",
      "Coronado",
      "Costa Mesa",
      "Culver cities",
      "Daly cities",
      "Davis",
      "Downey",
      "El Centro",
      "El Cerrito",
      "El Monte",
      "Escondido",
      "Eureka",
      "Fairfield",
      "Fontana",
      "Fremont",
      "Fresno",
      "Fullerton",
      "Garden Grove",
      "Glendale",
      "Hayward",
      "Hollywood",
      "Huntington Beach",
      "Indio",
      "Inglewood",
      "Irvine",
      "La Habra",
      "Laguna Beach",
      "Lancaster",
      "Livermore",
      "Lodi",
      "Lompoc",
      "Long Beach",
      "Los Angeles",
      "Malibu",
      "Martinez",
      "Marysville",
      "Menlo Park",
      "Merced",
      "Modesto",
      "Monterey",
      "Mountain View",
      "Napa",
      "Needles",
      "Newport Beach",
      "Norwalk",
      "Novato",
      "Oakland",
      "Oceanside",
      "Ojai",
      "Ontario",
      "Orange",
      "Oroville",
      "Oxnard",
      "Pacific Grove",
      "Palm Springs",
      "Palmdale",
      "Palo Alto",
      "Pasadena",
      "Petaluma",
      "Pomona",
      "Port Hueneme",
      "Rancho Cucamonga",
      "Red Bluff",
      "Redding",
      "Redlands",
      "Redondo Beach",
      "Redwood cities",
      "Richmond",
      "Riverside",
      "Roseville",
      "Sacramento",
      "Salinas",
      "San Bernardino",
      "San Clemente",
      "San Diego",
      "San Fernando",
      "San Francisco",
      "San Gabriel",
      "San Jose",
      "San Juan Capistrano",
      "San Leandro",
      "San Luis Obispo",
      "San Marino",
      "San Mateo",
      "San Pedro",
      "San Rafael",
      "San Simeon",
      "Santa Ana",
      "Santa Barbara",
      "Santa Clara",
      "Santa Clarita",
      "Santa Cruz",
      "Santa Monica",
      "Santa Rosa",
      "Sausalito",
      "Simi Valley",
      "Sonoma",
      "South San Francisco",
      "Stockton",
      "Sunnyvale",
      "Susanville",
      "Thousand Oaks",
      "Torrance",
      "Turlock",
      "Ukiah",
      "Vallejo",
      "Ventura",
      "Victorville",
      "Visalia",
      "Walnut Creek",
      "Watts",
      "West Covina",
      "Whittier",
      "Woodland",
      "Yorba Linda",
      "Yuba cities"
    ],
  },
  {
    "state": "Colorado",
    "cities": [
      "Alamosa",
      "Aspen",
      "Aurora",
      "Boulder",
      "Breckenridge",
      "Brighton",
      "Canon cities",
      "Central cities",
      "Climax",
      "Colorado Springs",
      "Cortez",
      "Cripple Creek",
      "Denver",
      "Durango",
      "Englewood",
      "Estes Park",
      "Fort Collins",
      "Fort Morgan",
      "Georgetown",
      "Glenwood Springs",
      "Golden",
      "Grand Junction",
      "Greeley",
      "Gunnison",
      "La Junta",
      "Leadville",
      "Littleton",
      "Longmont",
      "Loveland",
      "Montrose",
      "Ouray",
      "Pagosa Springs",
      "Pueblo",
      "Silverton",
      "Steamboat Springs",
      "Sterling",
      "Telluride",
      "Trinidad",
      "Vail",
      "Walsenburg",
      "Westminster"
    ],
  },
  {
    "state": "Connecticut",
    "cities": [
      "Ansonia",
      "Berlin",
      "Bloomfield",
      "Branford",
      "Bridgeport",
      "Bristol",
      "Coventry",
      "Danbury",
      "Darien",
      "Derby",
      "East Hartford",
      "East Haven",
      "Enfield",
      "Fairfield",
      "Farmington",
      "Greenwich",
      "Groton",
      "Guilford",
      "Hamden",
      "Hartford",
      "Lebanon",
      "Litchfield",
      "Manchester",
      "Mansfield",
      "Meriden",
      "Middletown",
      "Milford",
      "Mystic",
      "Naugatuck",
      "New Britain",
      "New Haven",
      "New London",
      "North Haven",
      "Norwalk",
      "Norwich",
      "Old Saybrook",
      "Orange",
      "Seymour",
      "Shelton",
      "Simsbury",
      "Southington",
      "Stamford",
      "Stonington",
      "Stratford",
      "Torrington",
      "Wallingford",
      "Waterbury",
      "Waterford",
      "Watertown",
      "West Hartford",
      "West Haven",
      "Westport",
      "Wethersfield",
      "Willimantic",
      "Windham",
      "Windsor",
      "Windsor Locks",
      "Winsted"
    ],
  },
  {
    "state": "Delaware",
    "cities": [
      "Dover",
      "Lewes",
      "Milford",
      "New Castle",
      "Newark",
      "Smyrna",
      "Wilmington"
    ],
  },
  {
    "state": "Florida",
    "cities": [
      "Apalachicola",
      "Bartow",
      "Belle Glade",
      "Boca Raton",
      "Bradenton",
      "Cape Coral",
      "Clearwater",
      "Cocoa Beach",
      "Cocoa-Rockledge",
      "Coral Gables",
      "Daytona Beach",
      "De Land",
      "Deerfield Beach",
      "Delray Beach",
      "Fernandina Beach",
      "Fort Lauderdale",
      "Fort Myers",
      "Fort Pierce",
      "Fort Walton Beach",
      "Gainesville",
      "Hallandale Beach",
      "Hialeah",
      "Hollywood",
      "Homestead",
      "Jacksonville",
      "Key West",
      "Lake cities",
      "Lake Wales",
      "Lakeland",
      "Largo",
      "Melbourne",
      "Miami",
      "Miami Beach",
      "Naples",
      "New Smyrna Beach",
      "Ocala",
      "Orlando",
      "Ormond Beach",
      "Palatka",
      "Palm Bay",
      "Palm Beach",
      "Panama cities",
      "Pensacola",
      "Pompano Beach",
      "Saint Augustine",
      "Saint Petersburg",
      "Sanford",
      "Sarasota",
      "Sebring",
      "Tallahassee",
      "Tampa",
      "Tarpon Springs",
      "Titusville",
      "Venice",
      "West Palm Beach",
      "White Springs",
      "Winter Haven",
      "Winter Park"
    ],
  },
  {
    "state": "Georgia",
    "cities": [
      "Albany",
      "Americus",
      "Andersonville",
      "Athens",
      "Atlanta",
      "Augusta",
      "Bainbridge",
      "Blairsville",
      "Brunswick",
      "Calhoun",
      "Carrollton",
      "Columbus",
      "Dahlonega",
      "Dalton",
      "Darien",
      "Decatur",
      "Douglas",
      "East Point",
      "Fitzgerald",
      "Fort Valley",
      "Gainesville",
      "La Grange",
      "Macon",
      "Marietta",
      "Milledgeville",
      "Plains",
      "Rome",
      "Savannah",
      "Toccoa",
      "Valdosta",
      "Warm Springs",
      "Warner Robins",
      "Washington",
      "Waycross"
    ],
  },
  {
    "state": "Hawaii",
    "cities": [
      "Hanalei",
      "Hilo",
      "Honaunau",
      "Honolulu",
      "Kahului",
      "Kaneohe",
      "Kapaa",
      "Kawaihae",
      "Lahaina",
      "Laie",
      "Wahiawa",
      "Wailuku",
      "Waimea"
    ],
  },
  {
    "state": "Idaho",
    "cities": [
      "Blackfoot",
      "Boise",
      "Bonners Ferry",
      "Caldwell",
      "Coeur d’Alene",
      "Idaho cities",
      "Idaho Falls",
      "Kellogg",
      "Lewiston",
      "Moscow",
      "Nampa",
      "Pocatello",
      "Priest River",
      "Rexburg",
      "Sun Valley",
      "Twin Falls"
    ],
  },
  {
    "state": "Illinois",
    "cities": [
      "Alton",
      "Arlington Heights",
      "Arthur",
      "Aurora",
      "Belleville",
      "Belvidere",
      "Bloomington",
      "Brookfield",
      "Cahokia",
      "Cairo",
      "Calumet cities",
      "Canton",
      "Carbondale",
      "Carlinville",
      "Carthage",
      "Centralia",
      "Champaign",
      "Charleston",
      "Chester",
      "Chicago",
      "Chicago Heights",
      "Cicero",
      "Collinsville",
      "Danville",
      "Decatur",
      "DeKalb",
      "Des Plaines",
      "Dixon",
      "East Moline",
      "East Saint Louis",
      "Effingham",
      "Elgin",
      "Elmhurst",
      "Evanston",
      "Freeport",
      "Galena",
      "Galesburg",
      "Glen Ellyn",
      "Glenview",
      "Granite cities",
      "Harrisburg",
      "Herrin",
      "Highland Park",
      "Jacksonville",
      "Joliet",
      "Kankakee",
      "Kaskaskia",
      "Kewanee",
      "La Salle",
      "Lake Forest",
      "Libertyville",
      "Lincoln",
      "Lisle",
      "Lombard",
      "Macomb",
      "Mattoon",
      "Moline",
      "Monmouth",
      "Mount Vernon",
      "Mundelein",
      "Naperville",
      "Nauvoo",
      "Normal",
      "North Chicago",
      "Oak Park",
      "Oregon",
      "Ottawa",
      "Palatine",
      "Park Forest",
      "Park Ridge",
      "Pekin",
      "Peoria",
      "Petersburg",
      "Pontiac",
      "Quincy",
      "Rantoul",
      "River Forest",
      "Rock Island",
      "Rockford",
      "Salem",
      "Shawneetown",
      "Skokie",
      "South Holland",
      "Springfield",
      "Streator",
      "Summit",
      "Urbana",
      "Vandalia",
      "Virden",
      "Waukegan",
      "Wheaton",
      "Wilmette",
      "Winnetka",
      "Wood River",
      "Zion"
    ],
  },
  {
    "state": "Indiana",
    "cities": [
      "Anderson",
      "Bedford",
      "Bloomington",
      "Columbus",
      "Connersville",
      "Corydon",
      "Crawfordsville",
      "East Chicago",
      "Elkhart",
      "Elwood",
      "Evansville",
      "Fort Wayne",
      "French Lick",
      "Gary",
      "Geneva",
      "Goshen",
      "Greenfield",
      "Hammond",
      "Hobart",
      "Huntington",
      "Indianapolis",
      "Jeffersonville",
      "Kokomo",
      "Lafayette",
      "Madison",
      "Marion",
      "Michigan cities",
      "Mishawaka",
      "Muncie",
      "Nappanee",
      "Nashville",
      "New Albany",
      "New Castle",
      "New Harmony",
      "Peru",
      "Plymouth",
      "Richmond",
      "Santa Claus",
      "Shelbyville",
      "South Bend",
      "Terre Haute",
      "Valparaiso",
      "Vincennes",
      "Wabash",
      "West Lafayette"
    ],
  },
  {
    "state": "Iowa",
    "cities": [
      "Amana Colonies",
      "Ames",
      "Boone",
      "Burlington",
      "Cedar Falls",
      "Cedar Rapids",
      "Charles cities",
      "Cherokee",
      "Clinton",
      "Council Bluffs",
      "Davenport",
      "Des Moines",
      "Dubuque",
      "Estherville",
      "Fairfield",
      "Fort Dodge",
      "Grinnell",
      "Indianola",
      "Iowa cities",
      "Keokuk",
      "Mason cities",
      "Mount Pleasant",
      "Muscatine",
      "Newton",
      "Oskaloosa",
      "Ottumwa",
      "Sioux cities",
      "Waterloo",
      "Webster cities",
      "West Des Moines"
    ],
  },
  {
    "state": "Kansas",
    "cities": [
      "Abilene",
      "Arkansas cities",
      "Atchison",
      "Chanute",
      "Coffeyville",
      "Council Grove",
      "Dodge cities",
      "Emporia",
      "Fort Scott",
      "Garden cities",
      "Great Bend",
      "Hays",
      "Hutchinson",
      "Independence",
      "Junction cities",
      "Kansas cities",
      "Lawrence",
      "Leavenworth",
      "Liberal",
      "Manhattan",
      "McPherson",
      "Medicine Lodge",
      "Newton",
      "Olathe",
      "Osawatomie",
      "Ottawa",
      "Overland Park",
      "Pittsburg",
      "Salina",
      "Shawnee",
      "Smith Center",
      "Topeka",
      "Wichita"
    ],
  },
  {
    "state": "Kentucky",
    "cities": [
      "Ashland",
      "Barbourville",
      "Bardstown",
      "Berea",
      "Boonesborough",
      "Bowling Green",
      "Campbellsville",
      "Covington",
      "Danville",
      "Elizabethtown",
      "Frankfort",
      "Harlan",
      "Harrodsburg",
      "Hazard",
      "Henderson",
      "Hodgenville",
      "Hopkinsville",
      "Lexington",
      "Louisville",
      "Mayfield",
      "Maysville",
      "Middlesboro",
      "Newport",
      "Owensboro",
      "Paducah",
      "Paris",
      "Richmond"
    ],
  },
  {
    "state": "Louisiana",
    "cities": [
      "Abbeville",
      "Alexandria",
      "Bastrop",
      "Baton Rouge",
      "Bogalusa",
      "Bossier cities",
      "Gretna",
      "Houma",
      "Lafayette",
      "Lake Charles",
      "Monroe",
      "Morgan cities",
      "Natchitoches",
      "New Iberia",
      "New Orleans",
      "Opelousas",
      "Ruston",
      "Saint Martinville",
      "Shreveport",
      "Thibodaux"
    ],
  },
  {
    "state": "Maine",
    "cities": [
      "Auburn",
      "Augusta",
      "Bangor",
      "Bar Harbor",
      "Bath",
      "Belfast",
      "Biddeford",
      "Boothbay Harbor",
      "Brunswick",
      "Calais",
      "Caribou",
      "Castine",
      "Eastport",
      "Ellsworth",
      "Farmington",
      "Fort Kent",
      "Gardiner",
      "Houlton",
      "Kennebunkport",
      "Kittery",
      "Lewiston",
      "Lubec",
      "Machias",
      "Orono",
      "Portland",
      "Presque Isle",
      "Rockland",
      "Rumford",
      "Saco",
      "Scarborough",
      "Waterville",
      "York"
    ],
  },
  {
    "state": "Maryland",
    "cities": [
      "Aberdeen",
      "Annapolis",
      "Baltimore",
      "Bethesda-Chevy Chase",
      "Bowie",
      "Cambridge",
      "Catonsville",
      "College Park",
      "Columbia",
      "Cumberland",
      "Easton",
      "Elkton",
      "Emmitsburg",
      "Frederick",
      "Greenbelt",
      "Hagerstown",
      "Hyattsville",
      "Laurel",
      "Oakland",
      "Ocean cities",
      "Rockville",
      "Saint Marys cities",
      "Salisbury",
      "Silver Spring",
      "Takoma Park",
      "Towson",
      "Westminster"
    ],
  },
  {
    "state": "Massachusetts",
    "cities": [
      "Abington",
      "Adams",
      "Amesbury",
      "Amherst",
      "Andover",
      "Arlington",
      "Athol",
      "Attleboro",
      "Barnstable",
      "Bedford",
      "Beverly",
      "Boston",
      "Bourne",
      "Braintree",
      "Brockton",
      "Brookline",
      "Cambridge",
      "Canton",
      "Charlestown",
      "Chelmsford",
      "Chelsea",
      "Chicopee",
      "Clinton",
      "Cohasset",
      "Concord",
      "Danvers",
      "Dartmouth",
      "Dedham",
      "Dennis",
      "Duxbury",
      "Eastham",
      "Edgartown",
      "Everett",
      "Fairhaven",
      "Fall River",
      "Falmouth",
      "Fitchburg",
      "Framingham",
      "Gloucester",
      "Great Barrington",
      "Greenfield",
      "Groton",
      "Harwich",
      "Haverhill",
      "Hingham",
      "Holyoke",
      "Hyannis",
      "Ipswich",
      "Lawrence",
      "Lenox",
      "Leominster",
      "Lexington",
      "Lowell",
      "Ludlow",
      "Lynn",
      "Malden",
      "Marblehead",
      "Marlborough",
      "Medford",
      "Milton",
      "Nahant",
      "Natick",
      "New Bedford",
      "Newburyport",
      "Newton",
      "North Adams",
      "Northampton",
      "Norton",
      "Norwood",
      "Peabody",
      "Pittsfield",
      "Plymouth",
      "statestown",
      "Quincy",
      "Randolph",
      "Revere",
      "Salem",
      "Sandwich",
      "Saugus",
      "Somerville",
      "South Hadley",
      "Springfield",
      "Stockbridge",
      "Stoughton",
      "Sturbridge",
      "Sudbury",
      "Taunton",
      "Tewksbury",
      "Truro",
      "Watertown",
      "Webster",
      "Wellesley",
      "Wellfleet",
      "West Bridgewater",
      "West Springfield",
      "Westfield",
      "Weymouth",
      "Whitman",
      "Williamstown",
      "Woburn",
      "Woods Hole",
      "Worcester"
    ],
  },
  {
    "state": "Michigan",
    "cities": [
      "Adrian",
      "Alma",
      "Ann Arbor",
      "Battle Creek",
      "Bay cities",
      "Benton Harbor",
      "Bloomfield Hills",
      "Cadillac",
      "Charlevoix",
      "Cheboygan",
      "Dearborn",
      "Detroit",
      "East Lansing",
      "Eastpointe",
      "Ecorse",
      "Escanaba",
      "Flint",
      "Grand Haven",
      "Grand Rapids",
      "Grayling",
      "Grosse Pointe",
      "Hancock",
      "Highland Park",
      "Holland",
      "Houghton",
      "Interlochen",
      "Iron Mountain",
      "Ironwood",
      "Ishpeming",
      "Jackson",
      "Kalamazoo",
      "Lansing",
      "Livonia",
      "Ludington",
      "Mackinaw cities",
      "Manistee",
      "Marquette",
      "Menominee",
      "Midland",
      "Monroe",
      "Mount Clemens",
      "Mount Pleasant",
      "Muskegon",
      "Niles",
      "Petoskey",
      "Pontiac",
      "Port Huron",
      "Royal Oak",
      "Saginaw",
      "Saint Ignace",
      "Saint Joseph",
      "Sault Sainte Marie",
      "Traverse cities",
      "Trenton",
      "Warren",
      "Wyandotte",
      "Ypsilanti"
    ],
  },
  {
    "state": "Minnesota",
    "cities": [
      "Albert Lea",
      "Alexandria",
      "Austin",
      "Bemidji",
      "Bloomington",
      "Brainerd",
      "Crookston",
      "Duluth",
      "Ely",
      "Eveleth",
      "Faribault",
      "Fergus Falls",
      "Hastings",
      "Hibbing",
      "International Falls",
      "Little Falls",
      "Mankato",
      "Minneapolis",
      "Moorhead",
      "New Ulm",
      "Northfield",
      "Owatonna",
      "Pipestone",
      "Red Wing",
      "Rochester",
      "Saint Cloud",
      "Saint Paul",
      "Sauk Centre",
      "South Saint Paul",
      "Stillwater",
      "Virginia",
      "Willmar",
      "Winona"
    ],
  },
  {
    "state": "Mississippi",
    "cities": [
      "Bay Saint Louis",
      "Biloxi",
      "Canton",
      "Clarksdale",
      "Columbia",
      "Columbus",
      "Corinth",
      "Greenville",
      "Greenwood",
      "Grenada",
      "Gulfport",
      "Hattiesburg",
      "Holly Springs",
      "Jackson",
      "Laurel",
      "Meridian",
      "Natchez",
      "Ocean Springs",
      "Oxford",
      "Pascagoula",
      "Pass Christian",
      "Philadelphia",
      "Port Gibson",
      "Starkville",
      "Tupelo",
      "Vicksburg",
      "West Point",
      "Yazoo cities"
    ],
  },
  {
    "state": "Missouri",
    "cities": [
      "Boonville",
      "Branson",
      "Cape Girardeau",
      "Carthage",
      "Chillicothe",
      "Clayton",
      "Columbia",
      "Excelsior Springs",
      "Ferguson",
      "Florissant",
      "Fulton",
      "Hannibal",
      "Independence",
      "Jefferson cities",
      "Joplin",
      "Kansas cities",
      "Kirksville",
      "Lamar",
      "Lebanon",
      "Lexington",
      "Maryville",
      "Mexico",
      "Monett",
      "Neosho",
      "New Madrid",
      "Rolla",
      "Saint Charles",
      "Saint Joseph",
      "Saint Louis",
      "Sainte Genevieve",
      "Salem",
      "Sedalia",
      "Springfield",
      "Warrensburg",
      "West Plains"
    ],
  },
  {
    "state": "Montana",
    "cities": [
      "Anaconda",
      "Billings",
      "Bozeman",
      "Butte",
      "Dillon",
      "Fort Benton",
      "Glendive",
      "Great Falls",
      "Havre",
      "Helena",
      "Kalispell",
      "Lewistown",
      "Livingston",
      "Miles cities",
      "Missoula",
      "Virginia cities"
    ],
  },
  {
    "state": "Nebraska",
    "cities": [
      "Beatrice",
      "Bellevue",
      "Boys Town",
      "Chadron",
      "Columbus",
      "Fremont",
      "Grand Island",
      "Hastings",
      "Kearney",
      "Lincoln",
      "McCook",
      "Minden",
      "Nebraska cities",
      "Norfolk",
      "North Platte",
      "Omaha",
      "Plattsmouth",
      "Red Cloud",
      "Sidney"
    ],
  },
  {
    "state": "Nevada",
    "cities": [
      "Boulder cities",
      "Carson cities",
      "Elko",
      "Ely",
      "Fallon",
      "Genoa",
      "Goldfield",
      "Henderson",
      "Las Vegas",
      "North Las Vegas",
      "Reno",
      "Sparks",
      "Virginia cities",
      "Winnemucca"
    ],
  },
  {
    "state": "New Hampshire",
    "cities": [
      "Berlin",
      "Claremont",
      "Concord",
      "Derry",
      "Dover",
      "Durham",
      "Exeter",
      "Franklin",
      "Hanover",
      "Hillsborough",
      "Keene",
      "Laconia",
      "Lebanon",
      "Manchester",
      "Nashua",
      "Peterborough",
      "Plymouth",
      "Portsmouth",
      "Rochester",
      "Salem",
      "Somersworth"
    ],
  },
  {
    "state": "New Jersey",
    "cities": [
      "Asbury Park",
      "Atlantic cities",
      "Bayonne",
      "Bloomfield",
      "Bordentown",
      "Bound Brook",
      "Bridgeton",
      "Burlington",
      "Caldwell",
      "Camden",
      "Cape May",
      "Clifton",
      "Cranford",
      "East Orange",
      "Edison",
      "Elizabeth",
      "Englewood",
      "Fort Lee",
      "Glassboro",
      "Hackensack",
      "Haddonfield",
      "Hoboken",
      "Irvington",
      "Jersey cities",
      "Lakehurst",
      "Lakewood",
      "Long Beach",
      "Long Branch",
      "Madison",
      "Menlo Park",
      "Millburn",
      "Millville",
      "Montclair",
      "Morristown",
      "Mount Holly",
      "New Brunswick",
      "New Milford",
      "Newark",
      "Ocean cities",
      "Orange",
      "Parsippany–Troy Hills",
      "Passaic",
      "Paterson",
      "Perth Amboy",
      "Plainfield",
      "Princeton",
      "Ridgewood",
      "Roselle",
      "Rutherford",
      "Salem",
      "Somerville",
      "South Orange Village",
      "Totowa",
      "Trenton",
      "Union",
      "Union cities",
      "Vineland",
      "Wayne",
      "Weehawken",
      "West New York",
      "West Orange",
      "Willingboro",
      "Woodbridge"
    ],
  },
  {
    "state": "New Mexico",
    "cities": [
      "Acoma",
      "Alamogordo",
      "Albuquerque",
      "Artesia",
      "Belen",
      "Carlsbad",
      "Clovis",
      "Deming",
      "Farmington",
      "Gallup",
      "Grants",
      "Hobbs",
      "Las Cruces",
      "Las Vegas",
      "Los Alamos",
      "Lovington",
      "Portales",
      "Raton",
      "Roswell",
      "Santa Fe",
      "Shiprock",
      "Silver cities",
      "Socorro",
      "Taos",
      "Truth or Consequences",
      "Tucumcari"
    ],
  },
  {
    "state": "New York",
    "cities": [
      "Albany",
      "Amsterdam",
      "Auburn",
      "Babylon",
      "Batavia",
      "Beacon",
      "Bedford",
      "Binghamton",
      "Bronx",
      "Brooklyn",
      "Buffalo",
      "Chautauqua",
      "Cheektowaga",
      "Clinton",
      "Cohoes",
      "Coney Island",
      "Cooperstown",
      "Corning",
      "Cortland",
      "Crown Point",
      "Dunkirk",
      "East Aurora",
      "East Hampton",
      "Eastchester",
      "Elmira",
      "Flushing",
      "Forest Hills",
      "Fredonia",
      "Garden cities",
      "Geneva",
      "Glens Falls",
      "Gloversville",
      "Great Neck",
      "Hammondsport",
      "Harlem",
      "Hempstead",
      "Herkimer",
      "Hudson",
      "Huntington",
      "Hyde Park",
      "Ilion",
      "Ithaca",
      "Jamestown",
      "Johnstown",
      "Kingston",
      "Lackawanna",
      "Lake Placid",
      "Levittown",
      "Lockport",
      "Mamaroneck",
      "Manhattan",
      "Massena",
      "Middletown",
      "Mineola",
      "Mount Vernon",
      "New Paltz",
      "New Rochelle",
      "New Windsor",
      "New York cities",
      "Newburgh",
      "Niagara Falls",
      "North Hempstead",
      "Nyack",
      "Ogdensburg",
      "Olean",
      "Oneida",
      "Oneonta",
      "Ossining",
      "Oswego",
      "Oyster Bay",
      "Palmyra",
      "Peekskill",
      "Plattsburgh",
      "Port Washington",
      "Potsdam",
      "Poughkeepsie",
      "Queens",
      "Rensselaer",
      "Rochester",
      "Rome",
      "Rotterdam",
      "Rye",
      "Sag Harbor",
      "Saranac Lake",
      "Saratoga Springs",
      "Scarsdale",
      "Schenectady",
      "Seneca Falls",
      "Southampton",
      "Staten Island",
      "Stony Brook",
      "Stony Point",
      "Syracuse",
      "Tarrytown",
      "Ticonderoga",
      "Tonawanda",
      "Troy",
      "Utica",
      "Watertown",
      "Watervliet",
      "Watkins Glen",
      "West Seneca",
      "White Plains",
      "Woodstock",
      "Yonkers"
    ],
  },
  {
    "state": "North Carolina",
    "cities": [
      "Asheboro",
      "Asheville",
      "Bath",
      "Beaufort",
      "Boone",
      "Burlington",
      "Chapel Hill",
      "Charlotte",
      "Concord",
      "Durham",
      "Edenton",
      "Elizabeth cities",
      "Fayetteville",
      "Gastonia",
      "Goldsboro",
      "Greensboro",
      "Greenville",
      "Halifax",
      "Henderson",
      "Hickory",
      "High Point",
      "Hillsborough",
      "Jacksonville",
      "Kinston",
      "Kitty Hawk",
      "Lumberton",
      "Morehead cities",
      "Morganton",
      "Nags Head",
      "New Bern",
      "Pinehurst",
      "Raleigh",
      "Rocky Mount",
      "Salisbury",
      "Shelby",
      "Washington",
      "Wilmington",
      "Wilson",
      "Winston-Salem"
    ],
  },
  {
    "state": "North Dakota",
    "cities": [
      "Bismarck",
      "Devils Lake",
      "Dickinson",
      "Fargo",
      "Grand Forks",
      "Jamestown",
      "Mandan",
      "Minot",
      "Rugby",
      "Valley cities",
      "Wahpeton",
      "Williston"
    ],
  },
  {
    "state": "Ohio",
    "cities": [
      "Akron",
      "Alliance",
      "Ashtabula",
      "Athens",
      "Barberton",
      "Bedford",
      "Bellefontaine",
      "Bowling Green",
      "Canton",
      "Chillicothe",
      "Cincinnati",
      "Cleveland",
      "Cleveland Heights",
      "Columbus",
      "Conneaut",
      "Cuyahoga Falls",
      "Dayton",
      "Defiance",
      "Delaware",
      "East Cleveland",
      "East Liverpool",
      "Elyria",
      "Euclid",
      "Findlay",
      "Gallipolis",
      "Greenville",
      "Hamilton",
      "Kent",
      "Kettering",
      "Lakewood",
      "Lancaster",
      "Lima",
      "Lorain",
      "Mansfield",
      "Marietta",
      "Marion",
      "Martins Ferry",
      "Massillon",
      "Mentor",
      "Middletown",
      "Milan",
      "Mount Vernon",
      "New Philadelphia",
      "Newark",
      "Niles",
      "North College Hill",
      "Norwalk",
      "Oberlin",
      "Painesville",
      "Parma",
      "Piqua",
      "Portsmouth",
      "Put-in-Bay",
      "Salem",
      "Sandusky",
      "Shaker Heights",
      "Springfield",
      "Steubenville",
      "Tiffin",
      "Toledo",
      "Urbana",
      "Warren",
      "Wooster",
      "Worthington",
      "Xenia",
      "Yellow Springs",
      "Youngstown",
      "Zanesville"
    ],
  },
  {
    "state": "Oklahoma",
    "cities": [
      "Ada",
      "Altus",
      "Alva",
      "Anadarko",
      "Ardmore",
      "Bartlesville",
      "Bethany",
      "Chickasha",
      "Claremore",
      "Clinton",
      "Cushing",
      "Duncan",
      "Durant",
      "Edmond",
      "El Reno",
      "Elk cities",
      "Enid",
      "Eufaula",
      "Frederick",
      "Guthrie",
      "Guymon",
      "Hobart",
      "Holdenville",
      "Hugo",
      "Lawton",
      "McAlester",
      "Miami",
      "Midwest cities",
      "Moore",
      "Muskogee",
      "Norman",
      "Oklahoma cities",
      "Okmulgee",
      "Pauls Valley",
      "Pawhuska",
      "Perry",
      "Ponca cities",
      "Pryor",
      "Sallisaw",
      "Sand Springs",
      "Sapulpa",
      "Seminole",
      "Shawnee",
      "Stillwater",
      "Tahlequah",
      "The Village",
      "Tulsa",
      "Vinita",
      "Wewoka",
      "Woodward"
    ],
  },
  {
    "state": "Oregon",
    "cities": [
      "Albany",
      "Ashland",
      "Astoria",
      "Baker cities",
      "Beaverton",
      "Bend",
      "Brookings",
      "Burns",
      "Coos Bay",
      "Corvallis",
      "Eugene",
      "Grants Pass",
      "Hillsboro",
      "Hood River",
      "Jacksonville",
      "John Day",
      "Klamath Falls",
      "La Grande",
      "Lake Oswego",
      "Lakeview",
      "McMinnville",
      "Medford",
      "Newberg",
      "Newport",
      "Ontario",
      "Oregon cities",
      "Pendleton",
      "Port Orford",
      "Portland",
      "Prineville",
      "Redmond",
      "Reedsport",
      "Roseburg",
      "Salem",
      "Seaside",
      "Springfield",
      "The Dalles",
      "Tillamook"
    ],
  },
  {
    "state": "Pennsylvania",
    "cities": [
      "Abington",
      "Aliquippa",
      "Allentown",
      "Altoona",
      "Ambridge",
      "Bedford",
      "Bethlehem",
      "Bloomsburg",
      "Bradford",
      "Bristol",
      "Carbondale",
      "Carlisle",
      "Chambersburg",
      "Chester",
      "Columbia",
      "Easton",
      "Erie",
      "Franklin",
      "Germantown",
      "Gettysburg",
      "Greensburg",
      "Hanover",
      "Harmony",
      "Harrisburg",
      "Hazleton",
      "Hershey",
      "Homestead",
      "Honesdale",
      "Indiana",
      "Jeannette",
      "Jim Thorpe",
      "Johnstown",
      "Lancaster",
      "Lebanon",
      "Levittown",
      "Lewistown",
      "Lock Haven",
      "Lower Southampton",
      "McKeesport",
      "Meadville",
      "Middletown",
      "Monroeville",
      "Nanticoke",
      "New Castle",
      "New Hope",
      "New Kensington",
      "Norristown",
      "Oil cities",
      "Philadelphia",
      "Phoenixville",
      "Pittsburgh",
      "Pottstown",
      "Pottsville",
      "Reading",
      "Scranton",
      "Shamokin",
      "Sharon",
      "State College",
      "Stroudsburg",
      "Sunbury",
      "Swarthmore",
      "Tamaqua",
      "Titusville",
      "Uniontown",
      "Warren",
      "Washington",
      "West Chester",
      "Wilkes-Barre",
      "Williamsport",
      "York"
    ],
  },
  {
    "state": "Rhode Island",
    "cities": [
      "Barrington",
      "Bristol",
      "Central Falls",
      "Cranston",
      "East Greenwich",
      "East Providence",
      "Kingston",
      "Middletown",
      "Narragansett",
      "Newport",
      "North Kingstown",
      "Pawtucket",
      "Portsmouth",
      "Providence",
      "South Kingstown",
      "Tiverton",
      "Warren",
      "Warwick",
      "Westerly",
      "Wickford",
      "Woonsocket"
    ],
  },
  {
    "state": "South Carolina",
    "cities": [
      "Abbeville",
      "Aiken",
      "Anderson",
      "Beaufort",
      "Camden",
      "Charleston",
      "Columbia",
      "Darlington",
      "Florence",
      "Gaffney",
      "Georgetown",
      "Greenville",
      "Greenwood",
      "Hartsville",
      "Lancaster",
      "Mount Pleasant",
      "Myrtle Beach",
      "Orangeburg",
      "Rock Hill",
      "Spartanburg",
      "Sumter",
      "Union"
    ],
  },
  {
    "state": "South Dakota",
    "cities": [
      "Aberdeen",
      "Belle Fourche",
      "Brookings",
      "Canton",
      "Custer",
      "De Smet",
      "Deadwood",
      "Hot Springs",
      "Huron",
      "Lead",
      "Madison",
      "Milbank",
      "Mitchell",
      "Mobridge",
      "Pierre",
      "Rapid cities",
      "Sioux Falls",
      "Spearfish",
      "Sturgis",
      "Vermillion",
      "Watertown",
      "Yankton"
    ],
  },
  {
    "state": "Tennessee",
    "cities": [
      "Alcoa",
      "Athens",
      "Chattanooga",
      "Clarksville",
      "Cleveland",
      "Columbia",
      "Cookeville",
      "Dayton",
      "Elizabethton",
      "Franklin",
      "Gallatin",
      "Gatlinburg",
      "Greeneville",
      "Jackson",
      "Johnson cities",
      "Jonesborough",
      "Kingsport",
      "Knoxville",
      "Lebanon",
      "Maryville",
      "Memphis",
      "Morristown",
      "Murfreesboro",
      "Nashville",
      "Norris",
      "Oak Ridge",
      "Shelbyville",
      "Tullahoma"
    ],
  },
  {
    "state": "Texas",
    "cities": [
      "Abilene",
      "Alpine",
      "Amarillo",
      "Arlington",
      "Austin",
      "Baytown",
      "Beaumont",
      "Big Spring",
      "Borger",
      "Brownsville",
      "Bryan",
      "Canyon",
      "Cleburne",
      "College Station",
      "Corpus Christi",
      "Crystal cities",
      "Dallas",
      "Del Rio",
      "Denison",
      "Denton",
      "Eagle Pass",
      "Edinburg",
      "El Paso",
      "Fort Worth",
      "Freeport",
      "Galveston",
      "Garland",
      "Goliad",
      "Greenville",
      "Harlingen",
      "Houston",
      "Huntsville",
      "Irving",
      "Johnson cities",
      "Kilgore",
      "Killeen",
      "Kingsville",
      "Laredo",
      "Longview",
      "Lubbock",
      "Lufkin",
      "Marshall",
      "McAllen",
      "McKinney",
      "Mesquite",
      "Midland",
      "Mission",
      "Nacogdoches",
      "New Braunfels",
      "Odessa",
      "Orange",
      "Pampa",
      "Paris",
      "Pasadena",
      "Pecos",
      "Pharr",
      "Plainview",
      "Plano",
      "Port Arthur",
      "Port Lavaca",
      "Richardson",
      "San Angelo",
      "San Antonio",
      "San Felipe",
      "San Marcos",
      "Sherman",
      "Sweetwater",
      "Temple",
      "Texarkana",
      "Texas cities",
      "Tyler",
      "Uvalde",
      "Victoria",
      "Waco",
      "Weatherford",
      "Wichita Falls",
      "Ysleta"
    ],
  },
  {
    "state": "Utah",
    "cities": [
      "Alta",
      "American Fork",
      "Bountiful",
      "Brigham cities",
      "Cedar cities",
      "Clearfield",
      "Delta",
      "Fillmore",
      "Green River",
      "Heber cities",
      "Kanab",
      "Layton",
      "Lehi",
      "Logan",
      "Manti",
      "Moab",
      "Monticello",
      "Murray",
      "Nephi",
      "Ogden",
      "Orderville",
      "Orem",
      "Panguitch",
      "Park cities",
      "Payson",
      "Price",
      "Provo",
      "Saint George",
      "Salt Lake cities",
      "Spanish Fork",
      "Springville",
      "Tooele",
      "Vernal"
    ],
  },
  {
    "state": "Vermont",
    "cities": [
      "Barre",
      "Bellows Falls",
      "Bennington",
      "Brattleboro",
      "Burlington",
      "Essex",
      "Manchester",
      "Middlebury",
      "Montpelier",
      "Newport",
      "Plymouth",
      "Rutland",
      "Saint Albans",
      "Saint Johnsbury",
      "Sharon",
      "Winooski"
    ],
  },
  {
    "state": "Virginia",
    "cities": [
      "Abingdon",
      "Alexandria",
      "Bristol",
      "Charlottesville",
      "Chesapeake",
      "Danville",
      "Fairfax",
      "Falls Church",
      "Fredericksburg",
      "Hampton",
      "Hanover",
      "Hopewell",
      "Lexington",
      "Lynchburg",
      "Manassas",
      "Martinsville",
      "New Market",
      "Newport News",
      "Norfolk",
      "Petersburg",
      "Portsmouth",
      "Reston",
      "Richmond",
      "Roanoke",
      "Staunton",
      "Suffolk",
      "Virginia Beach",
      "Waynesboro",
      "Williamsburg",
      "Winchester"
    ],
  },
  {
    "state": "Washington",
    "cities": [
      "Aberdeen",
      "Anacortes",
      "Auburn",
      "Bellevue",
      "Bellingham",
      "Bremerton",
      "Centralia",
      "Coulee Dam",
      "Coupeville",
      "Ellensburg",
      "Ephrata",
      "Everett",
      "Hoquiam",
      "Kelso",
      "Kennewick",
      "Longview",
      "Moses Lake",
      "Oak Harbor",
      "Olympia",
      "Pasco",
      "Point Roberts",
      "Port Angeles",
      "Pullman",
      "Puyallup",
      "Redmond",
      "Renton",
      "Richland",
      "Seattle",
      "Spokane",
      "Tacoma",
      "Vancouver",
      "Walla Walla",
      "Wenatchee",
      "Yakima"
    ],
  },
  {
    "state": "West Virginia",
    "cities": [
      "Bath",
      "Beckley",
      "Bluefield",
      "Buckhannon",
      "Charles Town",
      "Charleston",
      "Clarksburg",
      "Elkins",
      "Fairmont",
      "Grafton",
      "Harpers Ferry",
      "Hillsboro",
      "Hinton",
      "Huntington",
      "Keyser",
      "Lewisburg",
      "Logan",
      "Martinsburg",
      "Morgantown",
      "Moundsville",
      "New Martinsville",
      "Parkersburg",
      "Philippi",
      "Point Pleasant",
      "Princeton",
      "Romney",
      "Shepherdstown",
      "South Charleston",
      "Summersville",
      "Weirton",
      "Welch",
      "Wellsburg",
      "Weston",
      "Wheeling",
      "White Sulphur Springs",
      "Williamson"
    ],
  },
  {
    "state": "Wisconsin",
    "cities": [
      "Appleton",
      "Ashland",
      "Baraboo",
      "Belmont",
      "Beloit",
      "Eau Claire",
      "Fond du Lac",
      "Green Bay",
      "Hayward",
      "Janesville",
      "Kenosha",
      "La Crosse",
      "Lake Geneva",
      "Madison",
      "Manitowoc",
      "Marinette",
      "Menasha",
      "Milwaukee",
      "Neenah",
      "New Glarus",
      "Oconto",
      "Oshkosh",
      "Peshtigo",
      "Portage",
      "Prairie du Chien",
      "Racine",
      "Rhinelander",
      "Ripon",
      "Sheboygan",
      "Spring Green",
      "Stevens Point",
      "Sturgeon Bay",
      "Superior",
      "Waukesha",
      "Wausau",
      "Wauwatosa",
      "West Allis",
      "West Bend",
      "Wisconsin Dells"
    ],
  },
  {
    "state": "Wyoming",
    "cities": [
      "Buffalo",
      "Casper",
      "Cheyenne",
      "Cody",
      "Douglas",
      "Evanston",
      "Gillette",
      "Green River",
      "Jackson",
      "Lander",
      "Laramie",
      "Newcastle",
      "Powell",
      "Rawlins",
      "Riverton",
      "Rock Springs",
      "Sheridan",
      "Ten Sleep",
      "Thermopolis",
      "Torrington",
      "Worland"
    ],
  },
];

const List canadaStateCitiesList = [
  {
    "state": "Alberta", //province
    "cities": [
      "Airdrie",
      "Beaumont",
      "Brooks",
      "Calgary",
      "Camrose",
      "Chestermere",
      "Cold Lake",
      "Edmonton",
      "Fort Saskatchewan",
      "Grande Prairie",
      "Lacombe",
      "Leduc",
      "Lethbridge",
      "Lloydminster",
      "Medicine Hat",
      "Red Deer",
      "Spruce Grove",
      "St. Albert",
      "Wetaskiwin"
    ],
  },
  {
    "state": "British Columbia",
    "cities": [
      "Abbotsford",
      "Armstrong",
      "Burnaby",
      "Campbell River",
      "Castlegar",
      "Chilliwack",
      "Colwood",
      "Coquitlam",
      "Courtenay",
      "Cranbrook",
      "Dawson Creek",
      "Delta",
      "Duncan",
      "Enderby",
      "Fernie",
      "Fort St. John",
      "Grand Forks",
      "Greenwood",
      "Kamloops",
      "Kelowna",
      "Kimberley",
      "Langford",
      "Langley",
      "Maple Ridge",
      "Merritt",
      "Nanaimo",
      "Nelson",
      "New Westminster",
      "North Vancouver",
      "Parksville",
      "Penticton",
      "Pitt Meadows",
      "Port Alberni",
      "Port Coquitlam",
      "Port Moody",
      "Powell River",
      "Prince George",
      "Prince Rupert",
      "Quesnel",
      "Revelstoke",
      "Richmond",
      "Rossland",
      "Salmon Arm",
      "Surrey",
      "Terrace",
      "Trail",
      "Vancouver",
      "Vernon",
      "Victoria",
      "West Kelowna",
      "White Rock",
      "Williams Lake"
    ],
  },
  {
    "state": "Manitoba",
    "cities": [
      "Brandon",
      "Dauphin",
      "Flin Flon",
      "Morden",
      "Portage la Prairie",
      "Selkirk",
      "Steinbach",
      "Thompson",
      "Winkler",
      "Winnipeg"
    ],
  },
  {
    "state": "New Brunswick",
    "cities": [
      "Bathurst",
      "Campbellton",
      "Dieppe",
      "Edmundston",
      "Fredericton",
      "Miramichi",
      "Moncton",
      "Saint John"
    ],
  },
  {
    "state": "Newfoundland and Labrador",
    "cities": ["Corner Brook", "St. John's", "Mount Pearl"],
  },
  {
    "state": "Northwest Territories",
    "cities": ["Yellowknife"],
  },
  {
    "state": "Nunavut",
    "cities": ["Iqaluit"],
  },
  {
    "state": "Ontario",
    "cities": [
      "Barrie",
      "Belleville",
      "Brampton",
      "Brant",
      "Brantford",
      "Brockville",
      "Burlington",
      "Cambridge",
      "Clarence-Rockland",
      "Cornwall",
      "Dryden",
      "Elliot Lake",
      "Greater Sudbury",
      "Guelph",
      "Haldimand County",
      "Hamilton",
      "Kawartha Lakes",
      "Kenora",
      "Kingston",
      "Kitchener",
      "London",
      "Markham",
      "Mississauga",
      "Niagara Falls",
      "Norfolk County",
      "North Bay",
      "Orillia",
      "Oshawa",
      "Ottawa",
      "Owen Sound",
      "Pembroke",
      "Peterborough",
      "Pickering",
      "Port Colborne",
      "Prince Edward County",
      "Quinte West",
      "Richmond Hill",
      "Sarnia",
      "Sault Ste. Marie",
      "St. Catharines",
      "St. Thomas",
      "Stratford",
      "Temiskaming Shores",
      "Thorold",
      "Thunder Bay",
      "Timmins",
      "Toronto",
      "Vaughan",
      "Waterloo",
      "Welland",
      "Windsor",
      "Woodstock"
    ],
  },
  {
    "state": "Prince Edward Island",
    "cities": ["Charlottetown", "Summerside"],
  },
  {
    "state": "Quebec",
    "cities": [
      "Acton Vale",
      "Alma",
      "Amos",
      "Amqui",
      "Asbestos",
      "Baie-Comeau",
      "Baie-D'Urfé",
      "Baie-Saint-Paul",
      "Barkmere",
      "Beaconsfield",
      "Beauceville",
      "Beauharnois",
      "Beaupré",
      "Bécancour",
      "Bedford",
      "Belleterre",
      "Beloeil",
      "Berthierville",
      "Blainville",
      "Boisbriand",
      "Bois-des-Filion",
      "Bonaventure",
      "Boucherville",
      "Brome Lake",
      "Bromont",
      "Brossard",
      "Brownsburg-Chatham",
      "Candiac",
      "Cap-Chat",
      "Cap-Santé",
      "Carignan",
      "Carleton-sur-Mer",
      "Causapscal",
      "Chambly",
      "Chandler",
      "Chapais",
      "Charlemagne",
      "Châteauguay",
      "Château-Richer",
      "Chibougamau",
      "Clermont",
      "Coaticook",
      "Contrecoeur",
      "Cookshire-Eaton",
      "Côte Saint-Luc",
      "Coteau-du-Lac",
      "Cowansville",
      "Danville",
      "Daveluyville",
      "Dégelis",
      "Delson",
      "Desbiens",
      "Deux-Montagnes",
      "Disraeli",
      "Dolbeau-Mistassini",
      "Dollard-des-Ormeaux",
      "Donnacona",
      "Dorval",
      "Drummondville",
      "Dunham",
      "Duparquet",
      "East Angus",
      "Estérel",
      "Farnham",
      "Fermont",
      "Forestville",
      "Fossambault-sur-le-Lac",
      "Gaspé",
      "Gatineau",
      "Gracefield",
      "Granby",
      "Grande-Rivière",
      "Hampstead",
      "Hudson",
      "Huntingdon",
      "Joliette",
      "Kingsey Falls",
      "Kirkland",
      "La Malbaie",
      "La Pocatière",
      "La Prairie",
      "La Sarre",
      "La Tuque",
      "Lac-Delage",
      "Lachute",
      "Lac-Mégantic",
      "Lac-Saint-Joseph",
      "Lac-Sergent",
      "L'Ancienne-Lorette",
      "L'Assomption",
      "Laval",
      "Lavaltrie",
      "Lebel-sur-Quévillon",
      "L'Épiphanie",
      "Léry",
      "Lévis",
      "L'Île-Cadieux",
      "L'Île-Dorval",
      "L'Île-Perrot",
      "Longueuil",
      "Lorraine",
      "Louiseville",
      "Macamic",
      "Magog",
      "Malartic",
      "Maniwaki",
      "Marieville",
      "Mascouche",
      "Matagami",
      "Matane",
      "Mercier",
      "Métabetchouan–Lac-à-la-Croix",
      "Métis-sur-Mer",
      "Mirabel",
      "Mont-Joli",
      "Mont-Laurier",
      "Montmagny",
      "Montreal",
      "Montreal West",
      "Montréal-Est",
      "Mont-Saint-Hilaire",
      "Mont-Tremblant",
      "Mount Royal",
      "Murdochville",
      "Neuville",
      "New Richmond",
      "Nicolet",
      "Normandin",
      "Notre-Dame-de-l'Île-Perrot",
      "Notre-Dame-des-Prairies",
      "Otterburn Park",
      "Paspébiac",
      "Percé",
      "Pincourt",
      "Plessisville",
      "Pohénégamook",
      "Pointe-Claire",
      "Pont-Rouge",
      "Port-Cartier",
      "Portneuf",
      "Prévost",
      "Princeville",
      "Québec",
      "Repentigny",
      "Richelieu",
      "Richmond",
      "Rimouski",
      "Rivière-du-Loup",
      "Rivière-Rouge",
      "Roberval",
      "Rosemère",
      "Rouyn-Noranda",
      "Saguenay",
      "Saint-Augustin-de-Desmaures",
      "Saint-Basile",
      "Saint-Basile-le-Grand",
      "Saint-Bruno-de-Montarville",
      "Saint-Césaire",
      "Saint-Colomban",
      "Saint-Constant",
      "Sainte-Adèle",
      "Sainte-Agathe-des-Monts",
      "Sainte-Anne-de-Beaupré",
      "Sainte-Anne-de-Bellevue",
      "Sainte-Anne-des-Monts",
      "Sainte-Anne-des-Plaines",
      "Sainte-Catherine",
      "Sainte-Catherine-de-la-Jacques-Cartier",
      "Sainte-Julie",
      "Sainte-Marguerite-du-Lac-Masson",
      "Sainte-Marie",
      "Sainte-Marthe-sur-le-Lac",
      "Sainte-Thérèse",
      "Saint-Eustache",
      "Saint-Félicien",
      "Saint-Gabriel",
      "Saint-Georges",
      "Saint-Hyacinthe",
      "Saint-Jean-sur-Richelieu",
      "Saint-Jérôme",
      "Saint-Joseph-de-Beauce",
      "Saint-Joseph-de-Sorel",
      "Saint-Lambert",
      "Saint-Lazare",
      "Saint-Lin-Laurentides",
      "Saint-Marc-des-Carrières",
      "Saint-Ours",
      "Saint-Pamphile",
      "Saint-Pascal",
      "Saint-Pie",
      "Saint-Raymond",
      "Saint-Rémi",
      "Saint-Sauveur",
      "Saint-Tite",
      "Salaberry-de-Valleyfield",
      "Schefferville",
      "Scotstown",
      "Senneterre",
      "Sept-Îles",
      "Shawinigan",
      "Sherbrooke",
      "Sorel-Tracy",
      "Stanstead",
      "Sutton",
      "Témiscaming",
      "Témiscouata-sur-le-Lac",
      "Terrebonne",
      "Thetford Mines",
      "Thurso",
      "Trois-Pistoles",
      "Trois-Rivières",
      "Valcourt",
      "Val-d'Or",
      "Varennes",
      "Vaudreuil-Dorion",
      "Victoriaville",
      "Ville-Marie",
      "Warwick",
      "Waterloo",
      "Waterville",
      "Westmount",
      "Windsor"
    ],
  },
  {
    "state": "Yukon",
    "cities": ["Whitehorse"],
  },
  {
    "state": "Saskatchewan",
    "cities": [
      "Estevan",
      "Flin Flon",
      "Humboldt",
      "Lloydminster",
      "Martensville",
      "Meadow Lake",
      "Melfort",
      "Melville",
      "Moose Jaw",
      "North Battleford",
      "Prince Albert",
      "Regina",
      "Saskatoon",
      "Swift Current",
      "Warman",
      "Weyburn",
      "Yorkton"
    ],
  },
  {
    "state": "Nova Scotia",
    "cities": [],
  }
];

const ukStatesCitiesList = [
  {
    "state": "England",
    "cities": [
      "Bath",
      "Birmingham",
      "Bradford",
      "Brighton and Hove",
      "Bristol",
      "Cambridge",
      "Canterbury",
      "Carlisle",
      "Chelmsford",
      "Chester",
      "Chichester",
      "Colchester",
      "Coventry",
      "Derby",
      "Doncaster",
      "Durham",
      "Ely",
      "Exeter",
      "Gloucester",
      "Hereford",
      "Kingston upon Hull",
      "Lancaster",
      "Leeds",
      "Leicester",
      "Lichfield",
      "Lincoln",
      "Liverpool",
      "London",
      "Manchester",
      "Milton Keynes",
      "Newcastle upon Tyne",
      "Norwich",
      "Nottingham",
      "Oxford",
      "Peterborough",
      "Plymouth",
      "Portsmouth",
      "Preston",
      "Ripon",
      "Salford",
      "Salisbury",
      "Sheffield",
      "Southampton",
      "Southend-on-Sea",
      "St Albans",
      "Stoke-on-Trent",
      "Sunderland",
      "Truro",
      "Wakefield",
      "Wells",
      "Westminster",
      "Winchester",
      "Wolverhampton",
      "Worcester",
      "York"
    ]
  },
  {
    "state": "Scotland",
    "cities": [
      "Aberdeen",
      "Dundee",
      "Dunfermline",
      "Edinburgh",
      "Glasgow",
      "Inverness",
      "Perth",
      "Stirling"
    ]
  },
  {
    "state": "Wales",
    "cities": [
      "Bangor",
      "Cardiff",
      "Newport",
      "St Asaph",
      "St Davids",
      "Swansea",
      "Wrexham"
    ]
  },
  {
    "state": "Northern Ireland",
    "cities": ["Armagh", "Belfast", "Derry", "Lisburn", "Newry"]
  }
];

const germanyStatesCitiesList = [
  {
    "state": "Baden-Württemberg",
    "cities": [
      "Stuttgart",
      "Karlsruhe",
      "Mannheim",
      "Freiburg",
      "Heidelberg",
      "Ulm",
      "Heilbronn",
      "Pforzheim",
      "Reutlingen",
      "Tübingen"
    ]
  },
  {
    "state": "Bavaria (Bayern)",
    "cities": [
      "Munich",
      "Nuremberg",
      "Augsburg",
      "Regensburg",
      "Ingolstadt",
      "Würzburg",
      "Erlangen",
      "Bayreuth",
      "Bamberg",
      "Passau"
    ]
  },
  {
    "state": "Berlin",
    "cities": ["Berlin"]
  },
  {
    "state": "Brandenburg",
    "cities": [
      "Potsdam",
      "Cottbus",
      "Brandenburg an der Havel",
      "Frankfurt (Oder)",
      "Oranienburg"
    ]
  },
  {
    "state": "Bremen",
    "cities": ["Bremen", "Bremerhaven"]
  },
  {
    "state": "Hamburg",
    "cities": ["Hamburg"]
  },
  {
    "state": "Hesse (Hessen)",
    "cities": [
      "Frankfurt",
      "Wiesbaden",
      "Kassel",
      "Darmstadt",
      "Offenbach am Main",
      "Hanau",
      "Marburg",
      "Gießen",
      "Fulda"
    ]
  },
  {
    "state": "Lower Saxony (Niedersachsen)",
    "cities": [
      "Hanover",
      "Braunschweig",
      "Osnabrück",
      "Oldenburg",
      "Göttingen",
      "Wolfsburg",
      "Hildesheim",
      "Salzgitter"
    ]
  },
  {
    "state": "Mecklenburg-Vorpommern",
    "cities": [
      "Schwerin",
      "Rostock",
      "Neubrandenburg",
      "Stralsund",
      "Greifswald"
    ]
  },
  {
    "state": "North Rhine-Westphalia (Nordrhein-Westfalen)",
    "cities": [
      "Cologne",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Duisburg",
      "Bochum",
      "Wuppertal",
      "Bielefeld",
      "Bonn",
      "Münster",
      "Aachen",
      "Gelsenkirchen",
      "Mönchengladbach",
      "Krefeld",
      "Oberhausen"
    ]
  },
  {
    "state": "Rhineland-Palatinate (Rheinland-Pfalz)",
    "cities": [
      "Mainz",
      "Ludwigshafen",
      "Koblenz",
      "Trier",
      "Kaiserslautern",
      "Worms",
      "Speyer"
    ]
  },
  {
    "state": "Saarland",
    "cities": ["Saarbrücken", "Neunkirchen", "Homburg", "Völklingen"]
  },
  {
    "state": "Saxony (Sachsen)",
    "cities": ["Dresden", "Leipzig", "Chemnitz", "Zwickau", "Plauen", "Görlitz"]
  },
  {
    "state": "Saxony-Anhalt (Sachsen-Anhalt)",
    "cities": [
      "Magdeburg",
      "Halle (Saale)",
      "Dessau-Roßlau",
      "Wittenberg",
      "Stendal"
    ]
  },
  {
    "state": "Schleswig-Holstein",
    "cities": ["Kiel", "Lübeck", "Flensburg", "Neumünster", "Norderstedt"]
  },
  {
    "state": "Thuringia (Thüringen)",
    "cities": ["Erfurt", "Jena", "Gera", "Weimar", "Eisenach", "Suhl"]
  }
];
